### ISSUE TITLE
Adding/editing new alias throws error message

### ISSUE THREAD

**Issue by it-s** [bartzaalberg/alias#10]
Any time an alias is added or edited the following error message appears:

> Failed to execute child process “pantheon-terminal” (No such file or directory)

The alias is added successfully and functions in terminal as expected.
As far as I can tell, the pantheon-terminal has been renamed to io.elementary.terminal

**Comment by unbelievableflavour** [comment]
That's true, I will change that. Thanks

**Comment by unbelievableflavour** [comment]
Fixed it. Will be in the next release.

**Comment by unbelievableflavour** [comment]
@it-s it has been released. Could you check if it's fixed for you and close this ticket?
