### ISSUE TITLE
Alias should first check and then eventually offer adding new lines to .bashrc

### ISSUE THREAD

**Issue by DanyGee** [bartzaalberg/alias#11]
Default eOS .bashrc file already has...
```
# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
```
...code in it.
Alias should offer adding the...
```
#include_bash_aliases
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi;
```
...lines only if they don't exist in the .bashrc file already.

Now when the .bash_aliases file got created, and I removed the additional lines in .bashrc file created by Alias app, it prompts me to add them again when I launch the app.

**Comment by unbelievableflavour** [comment]
I didn't know elementary added that by default. I added a check and and now it won't happen again!
