### ISSUE TITLE
App does not work in fresh installed elementary OS 5.0 Juno x86_64

### ISSUE THREAD

**Issue by dignityinside** [bartzaalberg/alias#13]
When i start the app, i see an icon in the dock and after some seconds the app closes by itself without show any error.

**Comment by unbelievableflavour** [comment]
Oh damn. Will look at it Tomorrow.

**Comment by unbelievableflavour** [comment]
I'm sorry i can't seem to reproduce the problem... Did you install it through the app store? Are you on the latest version? Do other apps have the same problem?

**Comment by cassidyjames** [comment]
@bartzaalberg I'm also seeing this from master and the latest release through AppCenter Dashboard:

```
$ com.github.bartzaalberg.alias 
[INFO 13:34:50.576556] Application.vala:155: com.github.bartzaalberg.alias version: (null)
[INFO 13:34:50.576595] Application.vala:157: Kernel version: 4.18.0-13-generic
[FATAL 13:34:50.669322] [GLib] g_strsplit: assertion 'string != NULL' failed
Segmentation fault
```

**Comment by unbelievableflavour** [comment]
@cassidyjames i'm guessing you are not on a fresh install?

**Comment by cassidyjames** [comment]
@bartzaalberg I believe Alias was a fresh install here, but this was not on a fresh install of elementary OS.

**Comment by unbelievableflavour** [comment]
It's possible you already had an existing bash_aliases file and the format is a bit different. Could you please show me how your bash_aliases file looks? If it's not too much trouble ofcourse..

**Comment by unbelievableflavour** [comment]
Probably found the issue. I only supported alias commands. I now support also support export, and rest just won't be shown in app.

**Comment by unbelievableflavour** [comment]
Fixes have been released. Please try again.
