### ISSUE TITLE
Add Appdata and Desktop to translations

### ISSUE THREAD

**Issue by NathanBnm** [bartzaalberg/alias#17]
Translating `appdata.xml` and `.desktop` files will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

**Comment by unbelievableflavour** [comment]
Hi! I just pushed a release to dashboard. If it passes cert it should have translations for appcenter. BUT I have no way of testing this other than just pushing the release. So fingers crossed ^^

**Comment by unbelievableflavour** [comment]
Hi! Apparently it worked :) I now see the Dutch translation in Appcenter. Closing this.

**Comment by NathanBnm** [comment]
I just added French too in #19
