### ISSUE TITLE
Cant add aliases

### ISSUE THREAD

**Issue by fedexsca** [bartzaalberg/alias#22]
When I try to add a new alias pressing "Save" brings me to the main view (list of aliases) but the alias is not there.

**Comment by unbelievableflavour** [comment]
It is possible it is added but refresh isn't working anymore. Can you try to restart application and check if it's added?

**Comment by unbelievableflavour** [comment]
Should be fixed in release 1.5.2. Sorry for the long wait!

**Comment by unbelievableflavour** [comment]
Released and fixed.
