### ISSUE TITLE
Commands are not in quotes 

### ISSUE THREAD

**Issue by zvirdaniel** [bartzaalberg/alias#3]
**Example**
Name: test
Command: ls -l

When running `test` in bash it results in the following error: bash: `alias: -l: not found`

Solution is to use "ls -l" in command, you should _check_ whether the user has added the quotes by himself, and if not, add quotes around his command automatically.

**Comment by unbelievableflavour** [comment]
Sure. Will do!

**Comment by unbelievableflavour** [comment]
Fixed, added to master
