### ISSUE TITLE
Reboot is not required

### ISSUE THREAD

**Issue by zvirdaniel** [bartzaalberg/alias#4]
Your application has a note "Note: Changes take effect after relogging in" which is not necessarily true. Running `source ~/.bashrc` in bash makes all commands runnable instantly, without unnecessary relogging.

**Comment by unbelievableflavour** [comment]
oh Damn. That's awesome! I will add a call that will run that command whenever a save happens. So that this 'note' can be removed.

**Comment by unbelievableflavour** [comment]
Added to master
