### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by valicm** [bartzaalberg/alias#5]
On each application start, I don't get any app window. And after few seconds Alias just crash.

Each time the same error message is in syslog.

`Mar  1 22:42:59 valic-XPS-15-9560 kernel: [  751.345288] Alias[6469]: segfault at 8 ip 000000000040748e sp 00007ffc3cb41550 error 4 in com.github.bartzaalberg.alias[400000+11000]
Mar  1 22:43:32 valic-XPS-15-9560 kernel: [  784.175915] Alias[6527]: segfault at 8 ip 000000000040748e sp 00007ffea25031b0 error 4 in com.github.bartzaalberg.alias[400000+11000]
Mar  1 22:43:38 valic-XPS-15-9560 kernel: [  790.529249] Alias[6541]: segfault at 8 ip 000000000040748e sp 00007ffdb9f8ef00 error 4 in com.github.bartzaalberg.alias[400000+11000]
Mar  1 22:43:42 valic-XPS-15-9560 kernel: [  793.684661] Alias[6551]: segfault at 8 ip 000000000040748e sp 00007ffe712b0c00 error 4 in com.github.bartzaalberg.alias[400000+11000]
Mar  1 22:43:45 valic-XPS-15-9560 kernel: [  796.922712] Alias[6561]: segfault at 8 ip 000000000040748e sp 00007ffcabb03340 error 4 in com.github.bartzaalberg.alias[400000+11000]`

**OS data**
elementary OS 0.4.1 Loki
Linux 4.13.0-36-generic
GTK+ 3.18.9

**Affected Alias version**
0.1.0
0.0.3

**Comment by unbelievableflavour** [comment]
Is that immediately? or after seeing the welcome screen and clicking the button.

**Comment by valicm** [comment]
Immediately, I never have seen welcome screen at all :-)

**Comment by valicm** [comment]
Also when I am trying to run from terminal getting this message:

`valic@valic-XPS-15-9560:~$ com.github.bartzaalberg.alias
[INFO 09:32:45.037277] Application.vala:154: Alias version: 0.1.0
[INFO 09:32:45.037319] Application.vala:156: Kernel version: 4.13.0-36-generic
[FATAL 09:32:45.168210] [GLib] g_strsplit: assertion 'string != NULL' failed
Segmentation fault (core dumped)
`

**Comment by unbelievableflavour** [comment]
Well that's odd... Could it maybe be that a ~/.bash_aliases file already exists with wrong rights, or something is wrong with your ~/.bashrc file?

**Comment by valicm** [comment]
Yes, I have existing .bash_aliases file. When I remove it Alias is loaded correctly

**Comment by valicm** [comment]
Problem is with comments.

this cause crash:
`# drupal specific vagrants`
`alias dup7='cd ~/Development/drupal7 && vagrant up'`
`alias duh7='cd ~/srv/Development/drupal7 && vagrant halt'`

this is working
`alias dup7='cd ~/Development/drupal7 && vagrant up'`
`alias duh7='cd ~/srv/Development/drupal7 && vagrant halt'`

**Comment by valicm** [comment]
Can we add additional check for comments, 

similar to this in ResponseTranslator.vala with line split by #

`          while ((line = lines.read_line (null)) != null) {

                var comments = line.split ("#");

                if(line == "" || line == null || comments[0'] == "#"){
                    continue;
                }`

or maybe a better way, to list only lines which have alias return from the split function?

I am now first time in contact with Vala :-)

**Comment by unbelievableflavour** [comment]
Hahahah. That's ok. I will fix this! thanks

**Comment by unbelievableflavour** [comment]
Fixed, will be added to next release.
