### ISSUE TITLE
Do Zsh aliases as well

### ISSUE THREAD

**Issue by worldofpeace** [bartzaalberg/alias#6]

**Comment by unbelievableflavour** [comment]
Could you explain that a little better? I have never used Zsh.
As this link suggests( https://askubuntu.com/questions/31216/setting-up-aliases-in-zsh ) you can use the same file and aliases in ZSH. So do you mean i have to include the file in .zshrc?

**Comment by worldofpeace** [comment]
> As this link suggests( https://askubuntu.com/questions/31216/setting-up-aliases-in-zsh ) you can use the same file and aliases in ZSH. So do you mean i have to include the file in .zshrc?

Yep. If a someone has a .zshrc we can actually just append the same thing to the `.zshrc`
```
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi;
```

**Comment by worldofpeace** [comment]
@bartzaalberg 
https://github.com/bartzaalberg/alias/blob/9ee62c4e196b0718d2e56b483c650c0fcfa03493/src/ResponseTranslator.vala#L72
https://github.com/bartzaalberg/alias/blob/9ee62c4e196b0718d2e56b483c650c0fcfa03493/src/ResponseTranslator.vala#L82-L86
https://github.com/bartzaalberg/alias/blob/9ee62c4e196b0718d2e56b483c650c0fcfa03493/src/ResponseTranslator.vala#L88

Can you just have this write this string to the .zshrc if .zshrc exists?

**Comment by unbelievableflavour** [comment]
Hi, @worldofpeace sorry for the late reaction. i Created a branch with the feature included. I didn't have any time to test it but if you could try it out it would be of great help. Branch name is zsh-support.

**Comment by unbelievableflavour** [comment]
Ok, just to let you know. I'm not gonna merge the branch. Currently i am warning people that i am adding lines to the bashrc file. If I add ZSH i will also have to ask this for .zshrc which would make the app a lot less simplistic. I will however add an explanation to the readme how to do it. Closing this ticket.
