### ISSUE TITLE
[0.1.0] Alias fails to launch

### ISSUE THREAD

**Issue by xmwx38** [bartzaalberg/alias#8]
I am unable to successfully launch Alias.

**Comment by xmwx38** [comment]
![image](https://user-images.githubusercontent.com/2059090/39078744-c09069d6-44c2-11e8-93c6-698610dd0c06.png)

**Comment by unbelievableflavour** [comment]
Did you try the latest release? and if so, did that fix the problem? Or not. Sorry for the late reaction, i work from a mac now so i have less time on Elementary.

**Comment by xmwx38** [comment]
@bartzaalberg Yes.  I do believe the latest version fixed my issue.

Thanks.
